# Generated by Django 3.2.8 on 2022-08-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataWarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idwarga', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=100)),
                ('namawarga', models.CharField(max_length=100)),
                ('umur', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=100)),
            ],
        ),
    ]
