# Generated by Django 3.2.8 on 2022-08-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpenilaian', models.CharField(max_length=100)),
                ('kodealternatif', models.CharField(max_length=100)),
                ('namawarga', models.CharField(max_length=100)),
                ('statusrumah', models.CharField(max_length=100)),
                ('fasilitasrumah', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('penghasilan', models.CharField(max_length=100)),
                ('tanggungan', models.CharField(max_length=100)),
                ('kendaraan', models.CharField(max_length=100)),
            ],
        ),
    ]
