# Generated by Django 3.2.8 on 2022-08-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idsubkriteria', models.CharField(max_length=100)),
                ('idkriteria', models.CharField(max_length=100)),
                ('no', models.CharField(max_length=100)),
                ('kodekriteria', models.CharField(max_length=100)),
                ('namakriteria', models.CharField(max_length=100)),
                ('namasubkriteria', models.CharField(max_length=100)),
                ('nilai', models.CharField(max_length=100)),
            ],
        ),
    ]
