# Generated by Django 3.2.8 on 2022-08-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasubkriteria', '0003_auto_20220812_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubkriteria',
            name='namakriteria',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
