# Generated by Django 3.2.8 on 2022-08-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasubkriteria', '0004_datasubkriteria_namakriteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasubkriteria',
            name='kodekriteria',
        ),
        migrations.RemoveField(
            model_name='datasubkriteria',
            name='namasubkriteria',
        ),
        migrations.RemoveField(
            model_name='datasubkriteria',
            name='nilai',
        ),
    ]
