# Generated by Django 3.2.8 on 2022-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasubkriteria', '0005_auto_20220812_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubkriteria',
            name='kodekriteria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasubkriteria',
            name='namasubkriteria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datasubkriteria',
            name='nilai',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
